# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ASNMTAP
version:      3.000.004
version_from: 
installdirs:  site
requires:
    Bundle::LWP:                   1.11
    CGI:                           3.10
    Config::General:               2.30
    Config::General::Interpolated: 2.06
    Crypt::SSLeay:                 0.51
    Cwd:                           3.05
    Data::Dumper:                  2.121
    Date::Calc:                    5.4
    Digest::MD5:                   2.33
    Dumpvalue:                     1.11
    File::Basename:                2.73
    Getopt::Long:                  2.34
    IO:                            1.21
    IO::CaptureOutput:             1.03
    Mail::Sendmail:                0.79
    MIME::Base64:                  3.01
    Net::FTP:                      2.58
    Net::POP3:                     2.28
    SOAP::Lite:                    0.656
    Test::Simple:                  0.62
    Time::HiRes:                   1.76
    Time::Local:                   1.11
    URI:                           1.35
    XML::LibXML:                   1.58
    XML::Parser:                   2.34
    XML::Simple:                   2.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
